version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "octocat"
    assignees:
      - "octocat"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      prefix-development: "chore(dev)"
      include: "scope"
    versioning-strategy: auto
    rebase-strategy: auto
